    
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Amonsys Software Factory.
//     Template: Speed Developer FrameWork Version 1.0 (For Windows Applications)
//     Web Site: http://www.amonsys.com/SDF
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



using System;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Collections.Generic;
using ER.BE; 


namespace ER.DA
{
    public partial class TipoDocumentoDataAccessCollection
    {
 

        #region << Custom Stored Procedures >>
        
        
        #endregion
        
        /*public static TipoDocumentoEntityCollection LoadAll(SqlConnection conexion, SqlTransaction  transaction)
        {
            SqlCommand mCommand = new SqlCommand();
            SqlDataReader reader = null;
            try
            {
                mCommand.Connection = conexion;
                mCommand.CommandType = CommandType.StoredProcedure;
                mCommand.Transaction = transaction;
                
                mCommand.CommandText = "TipoDocumento_LoadAll";


                if (conexion.State != ConnectionState.Open) conexion.Open();
                reader = mCommand.ExecuteReader();

                TipoDocumentoEntityCollection tipoDocumentoEntityCollection = new TipoDocumentoEntityCollection();
                TipoDocumentoEntity tipoDocumentoEntity;
                
                while (reader.Read())
                {
                    tipoDocumentoEntity = new TipoDocumentoEntity();
                    
					tipoDocumentoEntity.Id = Convert.ToString(reader["Id"]);
					tipoDocumentoEntity.TipoDocumento = Convert.ToString(reader["TipoDocumento"]);
					tipoDocumentoEntity.IpIngreso = Convert.ToString(reader["IpIngreso"]);
					tipoDocumentoEntity.UsuarioIngreso = Convert.ToString(reader["UsuarioIngreso"]);
					tipoDocumentoEntity.FechaIngreso = Convert.ToDateTime(reader["FechaIngreso"]);
					if (reader["IpModificacion"] != DBNull.Value)
					{
						tipoDocumentoEntity.IpModificacion = Convert.ToString(reader["IpModificacion"]).ToUpper();
					}
					if (reader["UsuarioModificacion"] != DBNull.Value)
					{
						tipoDocumentoEntity.UsuarioModificacion = Convert.ToString(reader["UsuarioModificacion"]).ToUpper();
					}
					if (reader["FechaModificacion"] != DBNull.Value)
					{
						tipoDocumentoEntity.FechaModificacion = Convert.ToDateTime(reader["FechaModificacion"]);
					}
					tipoDocumentoEntity.IdEstado = Convert.ToInt16(reader["IdEstado"]);

                    
                    tipoDocumentoEntity.SetLoadedState();
                    tipoDocumentoEntityCollection.Add(tipoDocumentoEntity);
                    
                }

                return tipoDocumentoEntityCollection;
            }
            catch (Exception exc)
            {
                throw exc;
            }
            finally
            {
                if (reader != null) reader.Close();
                mCommand.Dispose();
            }

        }
        */
     
    //    public static TipoDocumentoEntityCollection FindByAll(TipoDocumentoFindParameterEntity findParameter , SqlConnection conexion, SqlTransaction  transaction)
    //    {
    //    	return FindByAll(findParameter,conexion,transaction,1);
    //    }
        
    //    public static TipoDocumentoEntityCollection FindByAll(TipoDocumentoFindParameterEntity findParameter , SqlConnection conexion, SqlTransaction  transaction, int deepLoadLevel)
    //    {
    //        SqlCommand mCommand = new SqlCommand();
    //        SqlDataReader reader = null;
    //        try
    //        {
    //            mCommand.Connection = conexion;
    //            mCommand.CommandType = CommandType.StoredProcedure;
    //            mCommand.Transaction = transaction;
    //            if (deepLoadLevel >= 1)
		  //   	{
    //            	mCommand.CommandText = "TipoDocumento_DeepFindByAll";
    //            }
    //            else mCommand.CommandText = "TipoDocumento_FindByAll";

                
				//if(!String.IsNullOrEmpty(findParameter.Id))
				//{
				//	mCommand.Parameters.AddWithValue("@Id", findParameter.Id );
				//}
				//else
				//{
				//	mCommand.Parameters.AddWithValue("@Id",DBNull.Value);
				//}

				//if(!String.IsNullOrEmpty(findParameter.TipoDocumento))
				//{
				//	mCommand.Parameters.AddWithValue("@TipoDocumento", findParameter.TipoDocumento );
				//}
				//else
				//{
				//	mCommand.Parameters.AddWithValue("@TipoDocumento",DBNull.Value);
				//}

				//if(!String.IsNullOrEmpty(findParameter.IpIngreso))
				//{
				//	mCommand.Parameters.AddWithValue("@IpIngreso", findParameter.IpIngreso );
				//}
				//else
				//{
				//	mCommand.Parameters.AddWithValue("@IpIngreso",DBNull.Value);
				//}

				//if(!String.IsNullOrEmpty(findParameter.UsuarioIngreso))
				//{
				//	mCommand.Parameters.AddWithValue("@UsuarioIngreso", findParameter.UsuarioIngreso );
				//}
				//else
				//{
				//	mCommand.Parameters.AddWithValue("@UsuarioIngreso",DBNull.Value);
				//}

				//if(findParameter.FechaIngreso != null && findParameter.FechaIngreso != DateTime.MinValue)
				//{
				//	mCommand.Parameters.AddWithValue("@FechaIngreso", findParameter.FechaIngreso);
				//}
				//else
				//{
				//	mCommand.Parameters.AddWithValue("@FechaIngreso",DBNull.Value);
				//}

				//if(!String.IsNullOrEmpty(findParameter.IpModificacion))
				//{
				//	mCommand.Parameters.AddWithValue("@IpModificacion", findParameter.IpModificacion );
				//}
				//else
				//{
				//	mCommand.Parameters.AddWithValue("@IpModificacion",DBNull.Value);
				//}

				//if(!String.IsNullOrEmpty(findParameter.UsuarioModificacion))
				//{
				//	mCommand.Parameters.AddWithValue("@UsuarioModificacion", findParameter.UsuarioModificacion );
				//}
				//else
				//{
				//	mCommand.Parameters.AddWithValue("@UsuarioModificacion",DBNull.Value);
				//}

				//if(findParameter.FechaModificacion != null && findParameter.FechaModificacion != DateTime.MinValue)
				//{
				//	mCommand.Parameters.AddWithValue("@FechaModificacion", findParameter.FechaModificacion);
				//}
				//else
				//{
				//	mCommand.Parameters.AddWithValue("@FechaModificacion",DBNull.Value);
				//}

				//if(findParameter.IdEstado != short.MinValue)
				//{
				//	mCommand.Parameters.AddWithValue("@IdEstado", findParameter.IdEstado);
				//}
				//else
				//{
				//	mCommand.Parameters.AddWithValue("@IdEstado",DBNull.Value);
				//}

    
               	
    //            if (conexion.State != ConnectionState.Open) conexion.Open();
    //            reader = mCommand.ExecuteReader();

    //            TipoDocumentoEntityCollection tipoDocumentoEntityCollection = new TipoDocumentoEntityCollection();
    //            TipoDocumentoEntity tipoDocumentoEntity;
                

    //            while (reader.Read())
    //            {
    //                tipoDocumentoEntity = new TipoDocumentoEntity();
				//	#region << Deep Load >>
    //                if (deepLoadLevel == 1)
		  //   		{

    //                }
	   //             #endregion                    
				//	tipoDocumentoEntity.Id = Convert.ToString(reader["Id"]);
				//	tipoDocumentoEntity.TipoDocumento = Convert.ToString(reader["TipoDocumento"]);
				//	tipoDocumentoEntity.IpIngreso = Convert.ToString(reader["IpIngreso"]);
				//	tipoDocumentoEntity.UsuarioIngreso = Convert.ToString(reader["UsuarioIngreso"]);
				//	tipoDocumentoEntity.FechaIngreso = Convert.ToDateTime(reader["FechaIngreso"]);
				//	if (reader["IpModificacion"] != DBNull.Value)
				//	{
				//		tipoDocumentoEntity.IpModificacion = Convert.ToString(reader["IpModificacion"]).ToUpper();
				//	}
				//	if (reader["UsuarioModificacion"] != DBNull.Value)
				//	{
				//		tipoDocumentoEntity.UsuarioModificacion = Convert.ToString(reader["UsuarioModificacion"]).ToUpper();
				//	}
				//	if (reader["FechaModificacion"] != DBNull.Value)
				//	{
				//		tipoDocumentoEntity.FechaModificacion = Convert.ToDateTime(reader["FechaModificacion"]);
				//	}
				//	tipoDocumentoEntity.IdEstado = Convert.ToInt16(reader["IdEstado"]);

                    
    //                tipoDocumentoEntity.SetLoadedState();
    //                tipoDocumentoEntityCollection.Add(tipoDocumentoEntity);
                    
    //            }

    //            return tipoDocumentoEntityCollection;
    //        }
    //        catch (Exception exc)
    //        {
    //            throw exc;
    //        }
    //        finally
    //        {
    //            if (reader != null) reader.Close();
    //            mCommand.Dispose();
    //        }

    //    }
        
    //    public static TipoDocumentoEntityCollection FindByAllPaged(TipoDocumentoFindParameterEntity findParameter , int pageNumber, int pageSize ,string orderBy, SqlConnection conexion, SqlTransaction  transaction )
    //    {
    //    	return FindByAllPaged(findParameter,pageNumber, pageSize,orderBy, conexion,transaction,1);
    //    }
        
    //    public static TipoDocumentoEntityCollection FindByAllPaged(TipoDocumentoFindParameterEntity findParameter , int pageNumber, int pageSize ,string orderBy, SqlConnection conexion ,SqlTransaction  transaction, int deepLoadLevel)
    //    {
    //        SqlCommand mCommand = new SqlCommand();
    //        SqlDataReader reader = null;
    //        try
    //        {
    //            mCommand.Connection = conexion;
    //            mCommand.CommandType = CommandType.StoredProcedure;
    //            mCommand.Transaction = transaction;
    //            if (deepLoadLevel >= 1)
		  //   	{
    //            	mCommand.CommandText = "TipoDocumento_DeepFindByAllPaged";
                	
    //            }
    //            else mCommand.CommandText = "TipoDocumento_FindByAllPaged";

                
				//if(!String.IsNullOrEmpty(findParameter.Id))
				//{
				//	mCommand.Parameters.AddWithValue("@Id", findParameter.Id );
				//}
				//else
				//{
				//	mCommand.Parameters.AddWithValue("@Id",DBNull.Value);
				//}

				//if(!String.IsNullOrEmpty(findParameter.TipoDocumento))
				//{
				//	mCommand.Parameters.AddWithValue("@TipoDocumento", findParameter.TipoDocumento );
				//}
				//else
				//{
				//	mCommand.Parameters.AddWithValue("@TipoDocumento",DBNull.Value);
				//}

				//if(!String.IsNullOrEmpty(findParameter.IpIngreso))
				//{
				//	mCommand.Parameters.AddWithValue("@IpIngreso", findParameter.IpIngreso );
				//}
				//else
				//{
				//	mCommand.Parameters.AddWithValue("@IpIngreso",DBNull.Value);
				//}

				//if(!String.IsNullOrEmpty(findParameter.UsuarioIngreso))
				//{
				//	mCommand.Parameters.AddWithValue("@UsuarioIngreso", findParameter.UsuarioIngreso );
				//}
				//else
				//{
				//	mCommand.Parameters.AddWithValue("@UsuarioIngreso",DBNull.Value);
				//}

				//if(findParameter.FechaIngreso != null && findParameter.FechaIngreso != DateTime.MinValue)
				//{
				//	mCommand.Parameters.AddWithValue("@FechaIngreso", findParameter.FechaIngreso);
				//}
				//else
				//{
				//	mCommand.Parameters.AddWithValue("@FechaIngreso",DBNull.Value);
				//}

				//if(!String.IsNullOrEmpty(findParameter.IpModificacion))
				//{
				//	mCommand.Parameters.AddWithValue("@IpModificacion", findParameter.IpModificacion );
				//}
				//else
				//{
				//	mCommand.Parameters.AddWithValue("@IpModificacion",DBNull.Value);
				//}

				//if(!String.IsNullOrEmpty(findParameter.UsuarioModificacion))
				//{
				//	mCommand.Parameters.AddWithValue("@UsuarioModificacion", findParameter.UsuarioModificacion );
				//}
				//else
				//{
				//	mCommand.Parameters.AddWithValue("@UsuarioModificacion",DBNull.Value);
				//}

				//if(findParameter.FechaModificacion != null && findParameter.FechaModificacion != DateTime.MinValue)
				//{
				//	mCommand.Parameters.AddWithValue("@FechaModificacion", findParameter.FechaModificacion);
				//}
				//else
				//{
				//	mCommand.Parameters.AddWithValue("@FechaModificacion",DBNull.Value);
				//}

				//if(findParameter.IdEstado != short.MinValue)
				//{
				//	mCommand.Parameters.AddWithValue("@IdEstado", findParameter.IdEstado);
				//}
				//else
				//{
				//	mCommand.Parameters.AddWithValue("@IdEstado",DBNull.Value);
				//}


				//mCommand.Parameters.AddWithValue("@PageNumber",pageNumber);
				//mCommand.Parameters.AddWithValue("@PageSize",pageSize);
				//if (deepLoadLevel > 1)
		  //   	{
				//	mCommand.Parameters.AddWithValue("@OrderBy",orderBy);
			 //   }
               	
    //            if (conexion.State != ConnectionState.Open) conexion.Open();
    //            reader = mCommand.ExecuteReader();

    //            TipoDocumentoEntityCollection tipoDocumentoEntityCollection = new TipoDocumentoEntityCollection();
    //            TipoDocumentoEntity tipoDocumentoEntity;
                

    //            while (reader.Read())
    //            {
    //                tipoDocumentoEntity = new TipoDocumentoEntity();
				//	#region << Deep Load >>
    //                if (deepLoadLevel > 1)
		  //   		{

    //                }
	   //             #endregion                    
				//	tipoDocumentoEntity.Id = Convert.ToString(reader["Id"]);
				//	tipoDocumentoEntity.TipoDocumento = Convert.ToString(reader["TipoDocumento"]);
				//	tipoDocumentoEntity.IpIngreso = Convert.ToString(reader["IpIngreso"]);
				//	tipoDocumentoEntity.UsuarioIngreso = Convert.ToString(reader["UsuarioIngreso"]);
				//	tipoDocumentoEntity.FechaIngreso = Convert.ToDateTime(reader["FechaIngreso"]);
				//	if (reader["IpModificacion"] != DBNull.Value)
				//	{
				//		tipoDocumentoEntity.IpModificacion = Convert.ToString(reader["IpModificacion"]).ToUpper();
				//	}
				//	if (reader["UsuarioModificacion"] != DBNull.Value)
				//	{
				//		tipoDocumentoEntity.UsuarioModificacion = Convert.ToString(reader["UsuarioModificacion"]).ToUpper();
				//	}
				//	if (reader["FechaModificacion"] != DBNull.Value)
				//	{
				//		tipoDocumentoEntity.FechaModificacion = Convert.ToDateTime(reader["FechaModificacion"]);
				//	}
				//	tipoDocumentoEntity.IdEstado = Convert.ToInt16(reader["IdEstado"]);

                    
    //                tipoDocumentoEntity.SetLoadedState();
    //                tipoDocumentoEntityCollection.Add(tipoDocumentoEntity);
                    
    //            }

    //            return tipoDocumentoEntityCollection;
    //        }
    //        catch (Exception exc)
    //        {
    //            throw exc;
    //        }
    //        finally
    //        {
    //            if (reader != null) reader.Close();
    //            mCommand.Dispose();
    //        }

    //    }
        
          
    }
}

