// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ER.DA.Models
{
    public partial class Categoria_LoadByPKResult
    {
        public int Id { get; set; }
        public int IdEmpresa { get; set; }
        public int IdLinea { get; set; }
        public string Categoria { get; set; }
        public string IpIngreso { get; set; }
        public string UsuarioIngreso { get; set; }
        public DateTime FechaIngreso { get; set; }
        public string IpModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public DateTime? FechaModificacion { get; set; }
        public short IdEstado { get; set; }
        public int Id_LineaFromIdLinea { get; set; }
        public int IdEmpresa_LineaFromIdLinea { get; set; }
        public int IdDivision_LineaFromIdLinea { get; set; }
        public string Linea_LineaFromIdLinea { get; set; }
        public string IpIngreso_LineaFromIdLinea { get; set; }
        public string UsuarioIngreso_LineaFromIdLinea { get; set; }
        public DateTime FechaIngreso_LineaFromIdLinea { get; set; }
        public string IpModificacion_LineaFromIdLinea { get; set; }
        public string UsuarioModificacion_LineaFromIdLinea { get; set; }
        public DateTime? FechaModificacion_LineaFromIdLinea { get; set; }
        public short IdEstado_LineaFromIdLinea { get; set; }
    }
}
