// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ER.DA.Models
{
    public partial class CierreCaja_LoadAllResult
    {
        public string ID { get; set; }
        public int IDEMPRESA { get; set; }
        public int IDLOCAL { get; set; }
        public string IDCAJERO { get; set; }
        public DateTime FECHAAPERTURA { get; set; }
        public DateTime? FECHACIERRE { get; set; }
        public string OBSERVACIONES { get; set; }
        [Column("SALDOINICIAL", TypeName = "decimal(18,2)")]
        public decimal SALDOINICIAL { get; set; }
        [Column("TOTALINGRESOS", TypeName = "decimal(18,2)")]
        public decimal TOTALINGRESOS { get; set; }
        [Column("TOTALEGRESOS", TypeName = "decimal(18,2)")]
        public decimal TOTALEGRESOS { get; set; }
        [Column("SALDOFINAL", TypeName = "decimal(18,2)")]
        public decimal SALDOFINAL { get; set; }
        public string IPINGRESO { get; set; }
        public string USUARIOINGRESO { get; set; }
        public DateTime FECHAINGRESO { get; set; }
        public string IPMODIFICACION { get; set; }
        public string USUARIOMODIFICACION { get; set; }
        public DateTime? FECHAMODIFICACION { get; set; }
        public short? IDESTADO { get; set; }
    }
}
