// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ER.DA.Models
{
    public partial class Custom_Stock_SaldoInventarioReportCliGOResult
    {
        public int Id { get; set; }
        public string Local { get; set; }
        [Column("Cantidad", TypeName = "decimal(18,2)")]
        public decimal? Cantidad { get; set; }
        public string Producto { get; set; }
    }
}
