// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ER.DA.Models
{
    public partial class Custom_Transfer_SearchResult
    {
        public string Id { get; set; }
        public string TipoTransaccion { get; set; }
        public string IdSalida { get; set; }
        public string IdEntrada { get; set; }
        public int? IdLocalOrigen { get; set; }
        public int? IdLocalDestino { get; set; }
        public int? IdEmpresa { get; set; }
        public string IdVendedor { get; set; }
        public string Periodo { get; set; }
        public DateTime? Fecha { get; set; }
        public string EstadoActual { get; set; }
        public string Observaciones { get; set; }
        public string IpIngreso { get; set; }
        public string UsuarioIngreso { get; set; }
        public DateTime? FechaIngreso { get; set; }
    }
}
