// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ER.DA.Models
{
    public partial class Custom_Entrada_SearchEntradaResult
    {
        public string Id { get; set; }
        public int IdEmpresa { get; set; }
        public int IdLocal { get; set; }
        public string IdVendedor { get; set; }
        public string Periodo { get; set; }
        public DateTime? Fecha { get; set; }
        public string TipoTransaccion { get; set; }
        public int? IdProveedor { get; set; }
        public string Ruc { get; set; }
        [Column("Subtotal0", TypeName = "decimal(18,2)")]
        public decimal? Subtotal0 { get; set; }
        [Column("Total", TypeName = "decimal(18,2)")]
        public decimal? Total { get; set; }
        [Column("Saldo", TypeName = "decimal(18,2)")]
        public decimal Saldo { get; set; }
        public string EstadoActual { get; set; }
        public int IdFormaPago { get; set; }
        public string IpIngreso { get; set; }
        public string UsuarioIngreso { get; set; }
        public DateTime FechaIngreso { get; set; }
        public string IpModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public DateTime? FechaModificacion { get; set; }
        public short IdEstado { get; set; }
        public string TransaccionPadre { get; set; }
        public string TipoTransaccionPadre { get; set; }
        public string Identificacion_EntidadFromIdProveedor { get; set; }
        public string RazonSocial_EntidadFromIdProveedor { get; set; }
    }
}
