// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ER.DA.Models
{
    public partial class DetalleCobro_DeepFindByAll3Result
    {
        public int Id { get; set; }
        public string IdCobroDebito { get; set; }
        public int IdCuentaPorCobrar { get; set; }
        public int IdMedioPago { get; set; }
        [Column("Valor", TypeName = "decimal(18,2)")]
        public decimal Valor { get; set; }
        public string Descripcion { get; set; }
        public string IpIngreso { get; set; }
        public string UsuarioIngreso { get; set; }
        public DateTime FechaIngreso { get; set; }
        public string IpModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public DateTime? FechaModificacion { get; set; }
        public short IdEstado { get; set; }
        public string IdCierreCaja { get; set; }
        public string Id_CobroDebitoFromIdCobroDebito { get; set; }
        public int IdEmpresa_CobroDebitoFromIdCobroDebito { get; set; }
        public DateTime Fecha_CobroDebitoFromIdCobroDebito { get; set; }
        public string Detalle_CobroDebitoFromIdCobroDebito { get; set; }
        public string IpIngreso_CobroDebitoFromIdCobroDebito { get; set; }
        public string UsuarioIngreso_CobroDebitoFromIdCobroDebito { get; set; }
        public DateTime FechaIngreso_CobroDebitoFromIdCobroDebito { get; set; }
        public string IpModificacion_CobroDebitoFromIdCobroDebito { get; set; }
        public string UsuarioModificacion_CobroDebitoFromIdCobroDebito { get; set; }
        public DateTime? FechaModificacion_CobroDebitoFromIdCobroDebito { get; set; }
        public short IdEstado_CobroDebitoFromIdCobroDebito { get; set; }
        public int Id_CuentaPorCobrarFromIdCuentaPorCobrar { get; set; }
        public string IdSalida_CuentaPorCobrarFromIdCuentaPorCobrar { get; set; }
        public int Numero_CuentaPorCobrarFromIdCuentaPorCobrar { get; set; }
        public DateTime FechaVencimiento_CuentaPorCobrarFromIdCuentaPorCobrar { get; set; }
        [Column("Valor_CuentaPorCobrarFromIdCuentaPorCobrar", TypeName = "decimal(18,2)")]
        public decimal Valor_CuentaPorCobrarFromIdCuentaPorCobrar { get; set; }
        [Column("Saldo_CuentaPorCobrarFromIdCuentaPorCobrar", TypeName = "decimal(18,2)")]
        public decimal? Saldo_CuentaPorCobrarFromIdCuentaPorCobrar { get; set; }
        public string IpIngreso_CuentaPorCobrarFromIdCuentaPorCobrar { get; set; }
        public string UsuarioIngreso_CuentaPorCobrarFromIdCuentaPorCobrar { get; set; }
        public DateTime FechaIngreso_CuentaPorCobrarFromIdCuentaPorCobrar { get; set; }
        public string IpModificacion_CuentaPorCobrarFromIdCuentaPorCobrar { get; set; }
        public string UsuarioModificacion_CuentaPorCobrarFromIdCuentaPorCobrar { get; set; }
        public DateTime? FechaModificacion_CuentaPorCobrarFromIdCuentaPorCobrar { get; set; }
        public short IdEstado_CuentaPorCobrarFromIdCuentaPorCobrar { get; set; }
        public int? Id_MedioPagoFromIdMedioPago { get; set; }
        public int? IdEmpresa_MedioPagoFromIdMedioPago { get; set; }
        public string MedioPago_MedioPagoFromIdMedioPago { get; set; }
        public string IpIngreso_MedioPagoFromIdMedioPago { get; set; }
        public string UsuarioIngreso_MedioPagoFromIdMedioPago { get; set; }
        public DateTime? FechaIngreso_MedioPagoFromIdMedioPago { get; set; }
        public string IpModificacion_MedioPagoFromIdMedioPago { get; set; }
        public string UsuarioModificacion_MedioPagoFromIdMedioPago { get; set; }
        public DateTime? FechaModificacion_MedioPagoFromIdMedioPago { get; set; }
        public short? IdEstado_MedioPagoFromIdMedioPago { get; set; }
    }
}
