// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ER.DA.Models;

public partial class Documento
{
    public string Id { get; set; }

    public string IdTipoDocumento { get; set; }

    public int IdEmpresa { get; set; }

    public string IdSalida { get; set; }

    public int IdEntidad { get; set; }

    public short IdMoneda { get; set; }

    public string Notas { get; set; }

    public string GuiaRemision { get; set; }

    public string NumeroDocumento { get; set; }

    public decimal Base0 { get; set; }

    public decimal BaseIva { get; set; }

    public decimal TotalDescuento { get; set; }

    public decimal? TotalSinImpuesto { get; set; }

    public decimal TotalIce { get; set; }

    public decimal TotalIva { get; set; }

    public decimal? Total { get; set; }

    public string FormaPago { get; set; }

    public int? IdFormaPagoSri { get; set; }

    public int Plazo { get; set; }

    public string UnidadTiempo { get; set; }

    public string IpIngreso { get; set; }

    public string UsuarioIngreso { get; set; }

    public DateTime FechaIngreso { get; set; }

    public string IpModificacion { get; set; }

    public string UsuarioModificacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public short IdEstado { get; set; }

    public string Ruc { get; set; }

    public string Establecimiento { get; set; }

    public string PuntoEmision { get; set; }

    public DateTime Fecha { get; set; }

    public bool ConsumidorFinal { get; set; }

    public long? IdFacturaGo { get; set; }

    public short Estado { get; set; }

    public string Mensaje { get; set; }

    public string NumeroAutorizacion { get; set; }

    public DateTime? FechaAutorizacion { get; set; }

    public virtual ICollection<DetalleDocumento> DetalleDocumento { get; set; } = new List<DetalleDocumento>();

    public virtual Entidad IdEntidadNavigation { get; set; }

    public virtual Moneda IdMonedaNavigation { get; set; }

    public virtual TipoDocumento IdTipoDocumentoNavigation { get; set; }
}