// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ER.DA.Models
{
    public partial class Entidad_LoadByTermDriverPagedResult
    {
        public int Id { get; set; }
        public int IdEmpresa { get; set; }
        public string TipoEntidad { get; set; }
        public string TipoIdentificacion { get; set; }
        public string RazonSocial { get; set; }
        public string Identificacion { get; set; }
        public short? IdPais { get; set; }
        public int? IdProvincia { get; set; }
        public int? IdCiudad { get; set; }
        public string Direccion { get; set; }
        public int? IdSector { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Correo { get; set; }
        public string Observaciones { get; set; }
        public string Foto { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
        public DateTime? FechaNacimiento { get; set; }
        public string Genero { get; set; }
        public string EstadoCivil { get; set; }
        public string Nacionalidad { get; set; }
        public string NivelEstudio { get; set; }
        public string Profesion { get; set; }
        public bool EsConsumidorFinal { get; set; }
    }
}
