// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ER.DA.Models;

public partial class FanId
{
    public int Id { get; set; }

    public int IdEntidad { get; set; }

    public Guid EventId { get; set; }

    public string GuestId { get; set; }

    public short IdEstado { get; set; }

    public int IdEmpresa { get; set; }

    public string NumeroOrden { get; set; }

    public string GuestId2 { get; set; }

    public virtual Entidad IdEntidadNavigation { get; set; }
}