// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ER.DA.Models
{
    public partial class InformacionAdicional_FindByAllResult
    {
        public int Id { get; set; }
        public string IdSalida { get; set; }
        public string TituloInfoAdicional { get; set; }
        public string InfoAdicional { get; set; }
    }
}
