// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ER.DA.Models;

public partial class LocalBodega
{
    public int Id { get; set; }

    public int IdEmpresa { get; set; }

    public string Tipo { get; set; }

    public string Local { get; set; }

    public string Direccion { get; set; }

    public string Telefono { get; set; }

    public string IpIngreso { get; set; }

    public string UsuarioIngreso { get; set; }

    public DateTime FechaIngreso { get; set; }

    public string IpModificacion { get; set; }

    public string UsuarioModificacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public short IdEstado { get; set; }

    public string DefaultRuc { get; set; }

    public string Establecimiento { get; set; }

    public string PuntoEmision { get; set; }

    public int? IdEntidad { get; set; }

    public string TipoGo { get; set; }

    public virtual ICollection<DetalleEntrada> DetalleEntrada { get; set; } = new List<DetalleEntrada>();

    public virtual ICollection<DetalleSalida> DetalleSalida { get; set; } = new List<DetalleSalida>();

    public virtual ICollection<Entrada> Entrada { get; set; } = new List<Entrada>();

    public virtual Empresa IdEmpresaNavigation { get; set; }

    public virtual ICollection<Salida> Salida { get; set; } = new List<Salida>();

    public virtual ICollection<UsuarioLocalBodega> UsuarioLocalBodega { get; set; } = new List<UsuarioLocalBodega>();
}