// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ER.DA.Models
{
    public partial class Precio_DeepFindByAllResult
    {
        public int Id { get; set; }
        public int IdProducto { get; set; }
        public int IdTipoUnidad { get; set; }
        [Column("Precio", TypeName = "decimal(18,2)")]
        public decimal Precio { get; set; }
        public int Moneda { get; set; }
        public bool IncluyeIva { get; set; }
        public string IpIngreso { get; set; }
        public string UsuarioIngreso { get; set; }
        public DateTime FechaIngreso { get; set; }
        public string IpModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public DateTime? FechaModificacion { get; set; }
        public short IdEstado { get; set; }
        public int Id_ProductoFromIdProducto { get; set; }
        public int IdEmpresa_ProductoFromIdProducto { get; set; }
        public string CodigoProveedor_ProductoFromIdProducto { get; set; }
        public string CodigoInterno_ProductoFromIdProducto { get; set; }
        public string TipoProducto_ProductoFromIdProducto { get; set; }
        public string Producto_ProductoFromIdProducto { get; set; }
        public string Descripcion_ProductoFromIdProducto { get; set; }
        public string DescipcionBusqueda_ProductoFromIdProducto { get; set; }
        public int Stock_ProductoFromIdProducto { get; set; }
        public int? StockMinimo_ProductoFromIdProducto { get; set; }
        [Column("Costo_ProductoFromIdProducto", TypeName = "decimal(18,4)")]
        public decimal Costo_ProductoFromIdProducto { get; set; }
        public int? UnidadMedida_ProductoFromIdProducto { get; set; }
        [Column("Descuento_ProductoFromIdProducto", TypeName = "decimal(18,2)")]
        public decimal? Descuento_ProductoFromIdProducto { get; set; }
        public bool? CobraIva_ProductoFromIdProducto { get; set; }
        public int? IdDivision_ProductoFromIdProducto { get; set; }
        public int? IdLinea_ProductoFromIdProducto { get; set; }
        public int? IdCategoria_ProductoFromIdProducto { get; set; }
        public int? IdMarca_ProductoFromIdProducto { get; set; }
        [Column("Peso_ProductoFromIdProducto", TypeName = "decimal(18,4)")]
        public decimal? Peso_ProductoFromIdProducto { get; set; }
        [Column("Volumen_ProductoFromIdProducto", TypeName = "decimal(18,4)")]
        public decimal? Volumen_ProductoFromIdProducto { get; set; }
        public string RegistroSanitario_ProductoFromIdProducto { get; set; }
        public string IpIngreso_ProductoFromIdProducto { get; set; }
        public string UsuarioIngreso_ProductoFromIdProducto { get; set; }
        public DateTime FechaIngreso_ProductoFromIdProducto { get; set; }
        public string IpModificacion_ProductoFromIdProducto { get; set; }
        public string UsuarioModificacion_ProductoFromIdProducto { get; set; }
        public DateTime? FechaModificacion_ProductoFromIdProducto { get; set; }
        public short IdEstado_ProductoFromIdProducto { get; set; }
        public int Id_TipoUnidadFromIdTipoUnidad { get; set; }
        public short IdEmpresa_TipoUnidadFromIdTipoUnidad { get; set; }
        public int IdProducto_TipoUnidadFromIdTipoUnidad { get; set; }
        public string TipoUnidad_TipoUnidadFromIdTipoUnidad { get; set; }
        [Column("Cantidad_TipoUnidadFromIdTipoUnidad", TypeName = "decimal(18,2)")]
        public decimal Cantidad_TipoUnidadFromIdTipoUnidad { get; set; }
        public int UnidadMedidad_TipoUnidadFromIdTipoUnidad { get; set; }
        public string IpIngreso_TipoUnidadFromIdTipoUnidad { get; set; }
        public string UsuarioIngreso_TipoUnidadFromIdTipoUnidad { get; set; }
        public DateTime FechaIngreso_TipoUnidadFromIdTipoUnidad { get; set; }
        public string IpModificacion_TipoUnidadFromIdTipoUnidad { get; set; }
        public string UsuarioModificacion_TipoUnidadFromIdTipoUnidad { get; set; }
        public DateTime? FechaModificacion_TipoUnidadFromIdTipoUnidad { get; set; }
        public short IdEstado_TipoUnidadFromIdTipoUnidad { get; set; }
    }
}
