// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ER.DA.Models;

public partial class Ruc
{
    public string Ruc1 { get; set; }

    public string RazonSocial { get; set; }

    public string ActividadEconomica { get; set; }

    public string Direccion { get; set; }

    public string Telefono { get; set; }

    public int? LocalPorDefecto { get; set; }

    public string TokenFactElectonica { get; set; }

    public int IdEmpresa { get; set; }

    public decimal LimiteFacturacion { get; set; }

    public decimal? TotalFacturado { get; set; }

    public string IpIngreso { get; set; }

    public string UsuarioIngreso { get; set; }

    public DateTime FechaIngreso { get; set; }

    public string IpModificacion { get; set; }

    public string UsuarioModificacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public short IdEstado { get; set; }

    public string NombreComercial { get; set; }

    public bool Rise { get; set; }

    public virtual ICollection<Entrada> Entrada { get; set; } = new List<Entrada>();

    public virtual Empresa IdEmpresaNavigation { get; set; }

    public virtual ICollection<PresupuestoFacturacion> PresupuestoFacturacion { get; set; } = new List<PresupuestoFacturacion>();

    public virtual ICollection<Salida> Salida { get; set; } = new List<Salida>();
}