// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ER.DA.Models;

public partial class RutaDetalle
{
    public int Id { get; set; }

    public int IdRuta { get; set; }

    public string IdSalidaEntrada { get; set; }

    public int IdLocal { get; set; }

    public int IdEntidadChofer { get; set; }

    public int? IdEntidadChoferRet { get; set; }

    public int IdVehiculo { get; set; }

    public DateTime Fecha { get; set; }

    public short IdEstado { get; set; }

    public int IdEmpresa { get; set; }

    public DateTime? FechaInicio { get; set; }

    public DateTime? FechaFin { get; set; }

    public virtual Ruta IdRutaNavigation { get; set; }

    public virtual ICollection<RutaImagenes> RutaImagenes { get; set; } = new List<RutaImagenes>();
}