// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ER.DA.Models
{
    public partial class Ruta_LoadByTermPagedResult
    {
        public int Id { get; set; }
        public int IdEntidad { get; set; }
        public string Estado { get; set; }
        public DateTime Fecha { get; set; }
        public string Descripcion { get; set; }
        public string RazonSocial { get; set; }
        public string Direccion { get; set; }
        public string Ciudad { get; set; }
        public string Celular { get; set; }
        public string Correo { get; set; }
        public int? IdBodega { get; set; }
        public string Local { get; set; }
        public int? IdLocalBodegaTransitoria { get; set; }
    }
}
