// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ER.DA.Models;

public partial class SalidaFormaPagoSri
{
    public long IdSalidaFormaPagoSri { get; set; }

    public int IdFormaPagoSri { get; set; }

    public string IdSalida { get; set; }

    public bool IdEstado { get; set; }

    public virtual FormaPagoSri IdFormaPagoSriNavigation { get; set; }

    public virtual Salida IdSalidaNavigation { get; set; }
}