// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ER.DA.Models;

public partial class TipoDescuento
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public bool? DescSobreDesc { get; set; }
}