    
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Amonsys Software Factory.
//     Template: Speed Developer FrameWork Version 1.0 (For Windows Applications)
//     Web Site: http://www.amonsys.com/SDF
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



#region using

using System;
using System.Collections.Generic;
using System.Data;

using System.Data.SqlClient;
using System.Net;
using ER.BE; 
using ER.DA; 
using System.Transactions;
using System.Configuration;

#endregion using

namespace ER.BA
{
    public partial class CategoriaBussinesAction
    {
         
       #region Implementation
        
       public static CategoriaEntity Save(CategoriaEntity categoria )
       {   
            return Save(categoria,null, null);
       }
       
       public static CategoriaEntity Save(CategoriaEntity categoria , SqlConnection connection, SqlTransaction transaction)
       {
            bool isBAParent = false;
            if (connection == null)
            {
                isBAParent = true; 
                connection = new SqlConnection(ConfigurationManager.AppSettings["TendaGo"]);
                connection.Open();
                transaction = connection.BeginTransaction(System.Data.IsolationLevel.ReadCommitted);

            }

            try
            {

//                using (TransactionScope transactionScope = new TransactionScope(TransactionScopeOption.Required))
//                {
/*
					if( categoria.IdLineaAsLinea != null && categoria.IdLineaAsLinea.CanSave )
					{
						categoria.IdLinea = LineaBussinesAction.Save(categoria.IdLineaAsLinea , connection,transaction).Id;
					}


*/
                    switch (categoria.CurrentState)
                    {
                        case EntityStatesEnum.Deleted:
                            CategoriaDataAccess.Delete(categoria, connection, transaction);
                            break;
                        case EntityStatesEnum.Updated:
                            CategoriaDataAccess.Update(categoria, connection, transaction);
                            break;
                        case EntityStatesEnum.New:
                            categoria = CategoriaDataAccess.Insert(categoria, connection, transaction);
                            break;
                        default:
                            break;
                    }
                    
                    

//                } 
               
               //End of Transaction
               if (isBAParent && transaction != null)
               {
					transaction.Commit();
					categoria.SetState(EntityStatesEnum.SavedSuccessfully);
               }
               
               return categoria;
            }
            catch (Exception exc)
            {
                if (isBAParent && transaction != null)
                {
                    transaction.Rollback();
                    if ( categoria != null)  categoria.RollBackState();
                    
                }
                throw exc;
            }
            finally
            {
                if (isBAParent) connection.Close();
            }
        }

  
         
         
         
        public static CategoriaEntity LoadByPK(int Id)
        {
            return LoadByPK(Id , null, null, 1);
        }
        public static CategoriaEntity LoadByPK(int Id ,int deepLoadLevel)
        {
            return LoadByPK(Id , null, null, deepLoadLevel);
        }
        
        public static CategoriaEntity LoadByPK(int Id, SqlConnection connection,SqlTransaction  transaction)
        {
            return LoadByPK(Id , connection, transaction, 1);
        }
        
        public static CategoriaEntity LoadByPK(int Id , SqlConnection connection,SqlTransaction  transaction,int deepLoadLevel)
        {
            bool isBAParent = false;
            if (connection == null)
            {
                isBAParent = true;
                connection = new SqlConnection(ConfigurationManager.AppSettings["TendaGo"]);

            }
            
            try
            {

                
				CategoriaEntity categoria = CategoriaDataAccess.LoadByPK(Id , connection, transaction, deepLoadLevel);
				if(categoria!=null) 
                {
					if (deepLoadLevel > 1)
	                {
							categoria.IdLineaAsLinea = LineaBussinesAction.LoadByPK(categoria.IdLinea, connection , transaction , deepLoadLevel - 1);

	                }
	                   
						categoria.SetLoadedState();
				}

				return categoria;
            }
            catch (Exception exc)
            {
                throw exc;
            }
            finally
            {
                if (isBAParent) connection.Close();
            }
        }
        
         
        #endregion Implementation
          
     }
}


