    
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Amonsys Software Factory.
//     Template: Speed Developer FrameWork Version 1.0 (For Windows Applications)
//     Web Site: http://www.amonsys.com/SDF
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



#region using

using System;
using System.Collections.Generic;
using System.Data;

using System.Data.SqlClient;
using System.Net;
using ER.BE; 
using ER.DA; 
using System.Transactions;
using System.Configuration;


#endregion using

namespace ER.BA
{
    public partial class TipoUnidadCollectionBussinesAction
    {
    
  
    
        #region << Custom Stored Procedures >>
        
        
        #endregion
        
        #region Implementation
        
        public static TipoUnidadEntityCollection Save(TipoUnidadEntityCollection tipoUnidadCollection )
        {
            return Save(tipoUnidadCollection, null, null);
        }
        
        public static TipoUnidadEntityCollection Save(TipoUnidadEntityCollection tipoUnidadCollection , SqlConnection connection, SqlTransaction transaction)
        {
            bool isBAParent = false;
            if (connection == null)
            {
                isBAParent = true;
                connection = new SqlConnection(ConfigurationManager.AppSettings["TendaGo"]);
                connection.Open();
                transaction = connection.BeginTransaction(System.Data.IsolationLevel.ReadCommitted);

            }

            try
            {

                    foreach (TipoUnidadEntity tipoUnidad in tipoUnidadCollection)
                    {
                        TipoUnidadBussinesAction.Save(tipoUnidad , connection, transaction);
                    }
                    
                    if (isBAParent && transaction != null) 
                    {
                    	transaction.Commit();
                    	tipoUnidadCollection.SetState(EntityStatesEnum.SavedSuccessfully);
                    }

                    return tipoUnidadCollection;
            }
            catch (Exception exc)
            {
                if (isBAParent && transaction != null)
                {
                    transaction.Rollback();
                    if ( tipoUnidadCollection != null)  tipoUnidadCollection.RollBackState();
                    
                }
                throw exc;
            }
            finally
            {
                if (isBAParent) connection.Close();
            }
        }

        #region << Find by All >>
        
        public static TipoUnidadEntityCollection FindByAll(TipoUnidadFindParameterEntity findParameter )
        {
        	return FindByAll(findParameter,null,null,1);
        }
        
        public static TipoUnidadEntityCollection FindByAll(TipoUnidadFindParameterEntity findParameter ,int deepLoadLevel)
        {
        	return FindByAll(findParameter,null,null,deepLoadLevel);
        }
        
        public static TipoUnidadEntityCollection FindByAll(TipoUnidadFindParameterEntity findParameter , SqlConnection connection,  SqlTransaction transaction)
        {
        	return FindByAll(findParameter,connection,transaction,1);
        }
        
        public static TipoUnidadEntityCollection FindByAll(TipoUnidadFindParameterEntity findParameter , SqlConnection connection,  SqlTransaction transaction,int deepLoadLevel)
        {
            bool isBAParent = false;
            if (connection == null)
            {
                isBAParent = true;
                connection = new SqlConnection(ConfigurationManager.AppSettings["TendaGo"]);

            }

			TipoUnidadEntityCollection tipoUnidadCollection = null; 

            try
            {

//                using (TransactionScope transactionScope = new TransactionScope(TransactionScopeOption.Required))
//                {
                   tipoUnidadCollection  = TipoUnidadDataAccessCollection.FindByAll(findParameter , connection, transaction, deepLoadLevel);
                   
				if (tipoUnidadCollection!=null && deepLoadLevel > 1)
                {
                	foreach (TipoUnidadEntity tipoUnidad in tipoUnidadCollection)
                    {
						tipoUnidad.IdProductoAsProducto = ProductoBussinesAction.LoadByPK(tipoUnidad.IdProducto, connection, transaction, deepLoadLevel - 1);
						tipoUnidad.UnidadMedidadAsUnidadMedida = UnidadMedidaBussinesAction.LoadByPK(tipoUnidad.UnidadMedidad, connection, transaction, deepLoadLevel - 1);

                    }

                }

                   
                   tipoUnidadCollection.SetState(EntityStatesEnum.Loaded);
//                    transactionScope.Complete();
//
//                }  //End of Transaction

                return tipoUnidadCollection;
            }
            catch (Exception exc)
            {
                throw exc;
            }
            finally
            {
                if (isBAParent) connection.Close();
            }
        }
        
        #endregion
        
        #region << Find by All Paged >>
        
        public static TipoUnidadEntityCollection FindByAllPaged(TipoUnidadFindParameterEntity findParameter, int pageNumber, int pageSize ,string orderBy)
        {
        	return FindByAllPaged(findParameter, pageNumber, pageSize,orderBy, null,null,1);
        }
        
        public static TipoUnidadEntityCollection FindByAllPaged(TipoUnidadFindParameterEntity findParameter , int pageNumber, int pageSize,string orderBy, int deepLoadLevel)
        {
        	return FindByAllPaged(findParameter, pageNumber, pageSize, orderBy, null,null,deepLoadLevel);
        }
        
        public static TipoUnidadEntityCollection FindByAllPaged(TipoUnidadFindParameterEntity findParameter , int pageNumber, int pageSize, string orderBy, SqlConnection connection,  SqlTransaction transaction)
        {
        	return FindByAllPaged(findParameter, pageNumber, pageSize, orderBy, connection,transaction,1);
        }
        
        public static TipoUnidadEntityCollection FindByAllPaged(TipoUnidadFindParameterEntity findParameter ,int pageNumber, int pageSize, string orderBy, SqlConnection connection,  SqlTransaction transaction,int deepLoadLevel)
        {
            bool isBAParent = false;
            if (connection == null)
            {
                isBAParent = true;
                connection = new SqlConnection(ConfigurationManager.AppSettings["TendaGo"]);

            }

			TipoUnidadEntityCollection tipoUnidadCollection = null; 

            try
            {

//                using (TransactionScope transactionScope = new TransactionScope(TransactionScopeOption.Required))
//                {
                   tipoUnidadCollection  = TipoUnidadDataAccessCollection.FindByAllPaged(findParameter , pageNumber, pageSize, orderBy, connection, transaction, deepLoadLevel);
                   tipoUnidadCollection.SetState(EntityStatesEnum.Loaded);
//                    transactionScope.Complete();
//
//                }  //End of Transaction

                return tipoUnidadCollection;
            }
            catch (Exception exc)
            {
                throw exc;
            }
            finally
            {
                if (isBAParent) connection.Close();
            }
        }
        
        #endregion

      
        #endregion Implementation
        
          
     }
}

