    
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Amonsys Software Factory.
//     Template: Speed Developer FrameWork Version 1.0 (For Windows Applications)
//     Web Site: http://www.amonsys.com/SDF
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



using System;
using System.Collections.Generic;
using System.Text;

namespace ER.BE
{
    [System.Serializable] 
    public partial class CuentaPorCobrarFindParameterEntity
    {
     
        #region << Atributtes >>

		private int _id = int.MinValue;
		private string _idSalida;
		private string _idSalida_DisplayMember;
		private int _numero = int.MinValue;
		private DateTime _fechaVencimiento;
		private decimal _valor = decimal.MinValue;
		private decimal _saldo = decimal.MinValue;
		private string _ipIngreso;
		private string _usuarioIngreso;
		private DateTime _fechaIngreso;
		private string _ipModificacion;
		private string _usuarioModificacion;
		private DateTime _fechaModificacion;
		private short _idEstado = short.MinValue;

        #endregion

        #region << Properties >>

		public int Id
		{
			get
			{
				return _id;
			}
			set
			{
				_id = value;
			}
		}

		public string IdSalida
		{
			get
			{
				return _idSalida;
			}
			set
			{
				_idSalida = value;
			}
		}

		public string IdSalida_DisplayMember
		{
			get
			{
				return _idSalida_DisplayMember;
			}
			set
			{
				_idSalida_DisplayMember = value;
			}
		}

		public int Numero
		{
			get
			{
				return _numero;
			}
			set
			{
				_numero = value;
			}
		}

		public DateTime FechaVencimiento
		{
			get
			{
				return _fechaVencimiento;
			}
			set
			{
				_fechaVencimiento = value;
			}
		}

		public decimal Valor
		{
			get
			{
				return _valor;
			}
			set
			{
				_valor = value;
			}
		}

		public decimal Saldo
		{
			get
			{
				return _saldo;
			}
			set
			{
				_saldo = value;
			}
		}

		public string IpIngreso
		{
			get
			{
				return _ipIngreso;
			}
			set
			{
				_ipIngreso = value;
			}
		}

		public string UsuarioIngreso
		{
			get
			{
				return _usuarioIngreso;
			}
			set
			{
				_usuarioIngreso = value;
			}
		}

		public DateTime FechaIngreso
		{
			get
			{
				return _fechaIngreso;
			}
			set
			{
				_fechaIngreso = value;
			}
		}

		public string IpModificacion
		{
			get
			{
				return _ipModificacion;
			}
			set
			{
				_ipModificacion = value;
			}
		}

		public string UsuarioModificacion
		{
			get
			{
				return _usuarioModificacion;
			}
			set
			{
				_usuarioModificacion = value;
			}
		}

		public DateTime FechaModificacion
		{
			get
			{
				return _fechaModificacion;
			}
			set
			{
				_fechaModificacion = value;
			}
		}

		public short IdEstado
		{
			get
			{
				return _idEstado;
			}
			set
			{
				_idEstado = value;
			}
		}

 
        #endregion

        public bool IsValid(CuentaPorCobrarEntity _entity)
        { 
			if(!String.IsNullOrEmpty(this.IdSalida))
			{
				if(this.IdSalida!=_entity.IdSalida)
				{
					return false;
				}
			}

			if(this.Numero != int.MinValue)
			{
				if(this.Numero!=_entity.Numero)
				{
					return false;
				}
			}

			if(this.FechaVencimiento != DateTime.MinValue)
			{
				if(this.FechaVencimiento!=_entity.FechaVencimiento)
				{
					return false;
				}
			}

			if(this.Valor != decimal.MinValue)
			{
				if(this.Valor!=_entity.Valor)
				{
					return false;
				}
			}

			if(this.Saldo != decimal.MinValue)
			{
				if(this.Saldo!=_entity.Saldo)
				{
					return false;
				}
			}

			if(!String.IsNullOrEmpty(this.IpIngreso))
			{
				if(this.IpIngreso!=_entity.IpIngreso)
				{
					return false;
				}
			}

			if(!String.IsNullOrEmpty(this.UsuarioIngreso))
			{
				if(this.UsuarioIngreso!=_entity.UsuarioIngreso)
				{
					return false;
				}
			}

			if(this.FechaIngreso != DateTime.MinValue)
			{
				if(this.FechaIngreso!=_entity.FechaIngreso)
				{
					return false;
				}
			}

			if(!String.IsNullOrEmpty(this.IpModificacion))
			{
				if(this.IpModificacion!=_entity.IpModificacion)
				{
					return false;
				}
			}

			if(!String.IsNullOrEmpty(this.UsuarioModificacion))
			{
				if(this.UsuarioModificacion!=_entity.UsuarioModificacion)
				{
					return false;
				}
			}

			if(this.FechaModificacion != DateTime.MinValue)
			{
				if(this.FechaModificacion!=_entity.FechaModificacion)
				{
					return false;
				}
			}

			if(this.IdEstado != short.MinValue)
			{
				if(this.IdEstado!=_entity.IdEstado)
				{
					return false;
				}
			}

     

			return true;       
        }

     

    }
}

