    
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Amonsys Software Factory.
//     Template: Speed Developer FrameWork Version 1.0 (For Windows Applications)
//     Web Site: http://www.amonsys.com/SDF
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



using System;
using System.Collections.Generic;
using System.Text;

namespace ER.BE
{
    [System.Serializable] 
    public partial class EntidadFindParameterEntity
    {
     
        #region << Atributtes >>

		private int _id = int.MinValue;
		private int _idEmpresa = int.MinValue;
		private string _tipoEntidad;
        private string _tipoIdentificacion;
        private string _razonSocial;
		private string _identificacion;
		private short _idPais = short.MinValue;
		private string _idPais_DisplayMember;
		private int _idProvincia = int.MinValue;
		private string _idProvincia_DisplayMember;
		private int _idCiudad = int.MinValue;
		private string _idCiudad_DisplayMember;
		private string _direccion;
		private int _idSector = int.MinValue;
		private string _idSector_DisplayMember;
		private string _telefono;
		private string _celular;
		private string _correo;
		private string _observaciones;
		private byte[] _foto;
		private string _ipIngreso;
		private string _usuarioIngreso;
		private DateTime _fechaIngreso;
		private string _ipModificacion;
		private string _usuarioModificacion;
		private DateTime _fechaModificacion;
		private short _idEstado = short.MinValue;
		private sbyte _esCliente = -1;
		private sbyte _esProveedor = -1;
		private string _latitud;
		private string _longitud;
		private sbyte _esConsumidorFinal = -1;

		#endregion

		#region << Properties >>

		public int Id
		{
			get
			{
				return _id;
			}
			set
			{
				_id = value;
			}
		}

		public int IdEmpresa
		{
			get
			{
				return _idEmpresa;
			}
			set
			{
				_idEmpresa = value;
			}
		}

		public string TipoEntidad
		{
			get
			{
				return _tipoEntidad;
			}
			set
			{
				_tipoEntidad = value;
			}
		}
        public string TipoIdentificacion
        {
            get
            {
                return _tipoIdentificacion;
            }
            set
            {
                _tipoIdentificacion = value;
            }
        }

        public string RazonSocial
		{
			get
			{
				return _razonSocial;
			}
			set
			{
				_razonSocial = value;
			}
		}

		public string Identificacion
		{
			get
			{
				return _identificacion;
			}
			set
			{
				_identificacion = value;
			}
		}

		public short IdPais
		{
			get
			{
				return _idPais;
			}
			set
			{
				_idPais = value;
			}
		}

		public string IdPais_DisplayMember
		{
			get
			{
				return _idPais_DisplayMember;
			}
			set
			{
				_idPais_DisplayMember = value;
			}
		}

		public int IdProvincia
		{
			get
			{
				return _idProvincia;
			}
			set
			{
				_idProvincia = value;
			}
		}

		public string IdProvincia_DisplayMember
		{
			get
			{
				return _idProvincia_DisplayMember;
			}
			set
			{
				_idProvincia_DisplayMember = value;
			}
		}

		public int IdCiudad
		{
			get
			{
				return _idCiudad;
			}
			set
			{
				_idCiudad = value;
			}
		}

		public string IdCiudad_DisplayMember
		{
			get
			{
				return _idCiudad_DisplayMember;
			}
			set
			{
				_idCiudad_DisplayMember = value;
			}
		}

		public string Direccion
		{
			get
			{
				return _direccion;
			}
			set
			{
				_direccion = value;
			}
		}

		public int IdSector
		{
			get
			{
				return _idSector;
			}
			set
			{
				_idSector = value;
			}
		}

		public string IdSector_DisplayMember
		{
			get
			{
				return _idSector_DisplayMember;
			}
			set
			{
				_idSector_DisplayMember = value;
			}
		}

		public string Telefono
		{
			get
			{
				return _telefono;
			}
			set
			{
				_telefono = value;
			}
		}

		public string Celular
		{
			get
			{
				return _celular;
			}
			set
			{
				_celular = value;
			}
		}

		public string Correo
		{
			get
			{
				return _correo;
			}
			set
			{
				_correo = value;
			}
		}

		public string Observaciones
		{
			get
			{
				return _observaciones;
			}
			set
			{
				_observaciones = value;
			}
		}

		public byte[] Foto
		{
			get
			{
				return _foto;
			}
			set
			{
				_foto = value;
			}
		}

		public string IpIngreso
		{
			get
			{
				return _ipIngreso;
			}
			set
			{
				_ipIngreso = value;
			}
		}

		public string UsuarioIngreso
		{
			get
			{
				return _usuarioIngreso;
			}
			set
			{
				_usuarioIngreso = value;
			}
		}

		public DateTime FechaIngreso
		{
			get
			{
				return _fechaIngreso;
			}
			set
			{
				_fechaIngreso = value;
			}
		}

		public string IpModificacion
		{
			get
			{
				return _ipModificacion;
			}
			set
			{
				_ipModificacion = value;
			}
		}

		public string UsuarioModificacion
		{
			get
			{
				return _usuarioModificacion;
			}
			set
			{
				_usuarioModificacion = value;
			}
		}

		public DateTime FechaModificacion
		{
			get
			{
				return _fechaModificacion;
			}
			set
			{
				_fechaModificacion = value;
			}
		}

		public short IdEstado
		{
			get
			{
				return _idEstado;
			}
			set
			{
				_idEstado = value;
			}
		}

		public sbyte EsCliente
		{
			get
			{
				return _esCliente;
			}
			set
			{
				_esCliente = value;
			}
		}

		public sbyte EsProveedor
		{
			get
			{
				return _esProveedor;
			}
			set
			{
				_esProveedor = value;
			}
		}

		public string Latitud 
		{
			get 
			{
				return _latitud;
			}
			set
			{
				_latitud = value;
			}
		}

		public string Longitud
		{
			get
			{
				return _longitud;
			}
			set
			{
				_longitud = value;
			}
		}

		public sbyte EsConsumidorFinal
		{
			get
			{
				return _esConsumidorFinal;
			}
			set
			{
				_esConsumidorFinal = value;
			}
		}

		#endregion

		public bool IsValid(EntidadEntity _entity)
        { 
			if(this.IdEmpresa != int.MinValue)
			{
				if(this.IdEmpresa!=_entity.IdEmpresa)
				{
					return false;
				}
			}

			if(!String.IsNullOrEmpty(this.TipoEntidad))
			{
				if(this.TipoEntidad!=_entity.TipoEntidad)
				{
					return false;
				}
			}

			if(!String.IsNullOrEmpty(this.RazonSocial))
			{
				if(this.RazonSocial!=_entity.RazonSocial)
				{
					return false;
				}
			}

			if(!String.IsNullOrEmpty(this.Identificacion))
			{
				if(this.Identificacion!=_entity.Identificacion)
				{
					return false;
				}
			}

			if(this.IdPais != short.MinValue)
			{
				if(this.IdPais!=_entity.IdPais)
				{
					return false;
				}
			}

			if(this.IdProvincia != int.MinValue)
			{
				if(this.IdProvincia!=_entity.IdProvincia)
				{
					return false;
				}
			}

			if(this.IdCiudad != int.MinValue)
			{
				if(this.IdCiudad!=_entity.IdCiudad)
				{
					return false;
				}
			}

			if(!String.IsNullOrEmpty(this.Direccion))
			{
				if(this.Direccion!=_entity.Direccion)
				{
					return false;
				}
			}

			if(this.IdSector != int.MinValue)
			{
				if(this.IdSector!=_entity.IdSector)
				{
					return false;
				}
			}

			if(!String.IsNullOrEmpty(this.Telefono))
			{
				if(this.Telefono!=_entity.Telefono)
				{
					return false;
				}
			}

			if(!String.IsNullOrEmpty(this.Celular))
			{
				if(this.Celular!=_entity.Celular)
				{
					return false;
				}
			}

			if(!String.IsNullOrEmpty(this.Correo))
			{
				if(this.Correo!=_entity.Correo)
				{
					return false;
				}
			}

			if(!String.IsNullOrEmpty(this.Observaciones))
			{
				if(this.Observaciones!=_entity.Observaciones)
				{
					return false;
				}
			}


			if(!String.IsNullOrEmpty(this.IpIngreso))
			{
				if(this.IpIngreso!=_entity.IpIngreso)
				{
					return false;
				}
			}

			if(!String.IsNullOrEmpty(this.UsuarioIngreso))
			{
				if(this.UsuarioIngreso!=_entity.UsuarioIngreso)
				{
					return false;
				}
			}

			if(this.FechaIngreso != DateTime.MinValue)
			{
				if(this.FechaIngreso!=_entity.FechaIngreso)
				{
					return false;
				}
			}

			if(!String.IsNullOrEmpty(this.IpModificacion))
			{
				if(this.IpModificacion!=_entity.IpModificacion)
				{
					return false;
				}
			}

			if(!String.IsNullOrEmpty(this.UsuarioModificacion))
			{
				if(this.UsuarioModificacion!=_entity.UsuarioModificacion)
				{
					return false;
				}
			}

			if(this.FechaModificacion != DateTime.MinValue)
			{
				if(this.FechaModificacion!=_entity.FechaModificacion)
				{
					return false;
				}
			}

			if(this.IdEstado != short.MinValue)
			{
				if(this.IdEstado!=_entity.IdEstado)
				{
					return false;
				}
			}

			if (!String.IsNullOrEmpty(this.Latitud))
			{
				if (this.Latitud != _entity.Latitud)
				{
					return false;
				}
			}

			if (!String.IsNullOrEmpty(this.Longitud))
			{
				if (this.Longitud != _entity.Longitud)
				{
					return false;
				}
			}

			return true;       
        }

     

    }
}

