    
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Amonsys Software Factory.
//     Template: Speed Developer FrameWork Version 1.0 (For Windows Applications)
//     Web Site: http://www.amonsys.com/SDF
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



using System;
using System.Collections.Generic;
using System.Text;

namespace ER.BE
{
    [System.Serializable] 
    public partial class PrecioFindParameterEntity
    {
     
        #region << Atributtes >>

		private int _id = int.MinValue;
		private int _idProducto = int.MinValue;
		private string _idProducto_DisplayMember;
		private int _idTipoUnidad = int.MinValue;
		private string _idTipoUnidad_DisplayMember;
		private decimal _precio = decimal.MinValue;
		private int _moneda = int.MinValue;
		private sbyte  _incluyeIva=-1;
		private string _ipIngreso;
		private string _usuarioIngreso;
		private DateTime _fechaIngreso;
		private string _ipModificacion;
		private string _usuarioModificacion;
		private DateTime _fechaModificacion;
		private short _idEstado = short.MinValue;

        #endregion

        #region << Properties >>

		public int Id
		{
			get
			{
				return _id;
			}
			set
			{
				_id = value;
			}
		}

		public int IdProducto
		{
			get
			{
				return _idProducto;
			}
			set
			{
				_idProducto = value;
			}
		}

		public string IdProducto_DisplayMember
		{
			get
			{
				return _idProducto_DisplayMember;
			}
			set
			{
				_idProducto_DisplayMember = value;
			}
		}

		public int IdTipoUnidad
		{
			get
			{
				return _idTipoUnidad;
			}
			set
			{
				_idTipoUnidad = value;
			}
		}

		public string IdTipoUnidad_DisplayMember
		{
			get
			{
				return _idTipoUnidad_DisplayMember;
			}
			set
			{
				_idTipoUnidad_DisplayMember = value;
			}
		}

		public decimal Precio
		{
			get
			{
				return _precio;
			}
			set
			{
				_precio = value;
			}
		}

		public int Moneda
		{
			get
			{
				return _moneda;
			}
			set
			{
				_moneda = value;
			}
		}

		public sbyte IncluyeIva
		{
			get
			{
				return _incluyeIva;
			}
			set
			{
				_incluyeIva = value;
			}
		}

		public string IpIngreso
		{
			get
			{
				return _ipIngreso;
			}
			set
			{
				_ipIngreso = value;
			}
		}

		public string UsuarioIngreso
		{
			get
			{
				return _usuarioIngreso;
			}
			set
			{
				_usuarioIngreso = value;
			}
		}

		public DateTime FechaIngreso
		{
			get
			{
				return _fechaIngreso;
			}
			set
			{
				_fechaIngreso = value;
			}
		}

		public string IpModificacion
		{
			get
			{
				return _ipModificacion;
			}
			set
			{
				_ipModificacion = value;
			}
		}

		public string UsuarioModificacion
		{
			get
			{
				return _usuarioModificacion;
			}
			set
			{
				_usuarioModificacion = value;
			}
		}

		public DateTime FechaModificacion
		{
			get
			{
				return _fechaModificacion;
			}
			set
			{
				_fechaModificacion = value;
			}
		}

		public short IdEstado
		{
			get
			{
				return _idEstado;
			}
			set
			{
				_idEstado = value;
			}
		}

 
        #endregion

        public bool IsValid(PrecioEntity _entity)
        { 
			if(this.IdProducto != int.MinValue)
			{
				if(this.IdProducto!=_entity.IdProducto)
				{
					return false;
				}
			}

			if(this.IdTipoUnidad != int.MinValue)
			{
				if(this.IdTipoUnidad!=_entity.IdTipoUnidad)
				{
					return false;
				}
			}

			if(this.Precio != decimal.MinValue)
			{
				if(this.Precio!=_entity.Precio)
				{
					return false;
				}
			}

			if(this.Moneda != int.MinValue)
			{
				if(this.Moneda!=_entity.Moneda)
				{
					return false;
				}
			}

			if(this.IncluyeIva != -1)
			{
				if (this.IncluyeIva == 1)
				{
					if(!_entity.IncluyeIva)
					{
						return false;
					}
				}
				else
				{
					if(_entity.IncluyeIva)
					{
						return false;
					}
				}
			}
				//else
				//{
				//}

			if(!String.IsNullOrEmpty(this.IpIngreso))
			{
				if(this.IpIngreso!=_entity.IpIngreso)
				{
					return false;
				}
			}

			if(!String.IsNullOrEmpty(this.UsuarioIngreso))
			{
				if(this.UsuarioIngreso!=_entity.UsuarioIngreso)
				{
					return false;
				}
			}

			if(this.FechaIngreso != DateTime.MinValue)
			{
				if(this.FechaIngreso!=_entity.FechaIngreso)
				{
					return false;
				}
			}

			if(!String.IsNullOrEmpty(this.IpModificacion))
			{
				if(this.IpModificacion!=_entity.IpModificacion)
				{
					return false;
				}
			}

			if(!String.IsNullOrEmpty(this.UsuarioModificacion))
			{
				if(this.UsuarioModificacion!=_entity.UsuarioModificacion)
				{
					return false;
				}
			}

			if(this.FechaModificacion != DateTime.MinValue)
			{
				if(this.FechaModificacion!=_entity.FechaModificacion)
				{
					return false;
				}
			}

			if(this.IdEstado != short.MinValue)
			{
				if(this.IdEstado!=_entity.IdEstado)
				{
					return false;
				}
			}

     

			return true;       
        }

     

    }
}

