    
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Amonsys Software Factory.
//     Template: Speed Developer FrameWork Version 1.0 (For Windows Applications)
//     Web Site: http://www.amonsys.com/SDF
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



using System;
using System.Collections.Generic;
using System.Text;

namespace ER.BE
{
    
    [System.Serializable] 
    public partial class PresupuestoFacturacionEntityBase : EntityStatesManager
    
    {

        #region << Columns >>

		public const string Id_EntityColumn = "Id";
		public const string IdEmpresa_EntityColumn = "IdEmpresa";
		public const string IdEmpresaAsEmpresa_EntityColumn = "IdEmpresaAsEmpresa";
		public const string IdEmpresa_DisplayMember_EntityColumn = "IdEmpresa_DisplayMember";
		public const string Ruc_EntityColumn = "Ruc";
		public const string RucAsRuc_EntityColumn = "RucAsRuc";
		public const string Ruc_DisplayMember_EntityColumn = "Ruc_DisplayMember";
		public const string Mes_EntityColumn = "Mes";
		public const string Fecha_EntityColumn = "Fecha";
		public const string Presupuesto_EntityColumn = "Presupuesto";
		public const string IpIngreso_EntityColumn = "IpIngreso";
		public const string UsuarioIngreso_EntityColumn = "UsuarioIngreso";
		public const string FechaIngreso_EntityColumn = "FechaIngreso";
		public const string IpModificacion_EntityColumn = "IpModificacion";
		public const string UsuarioModificacion_EntityColumn = "UsuarioModificacion";
		public const string FechaModificacion_EntityColumn = "FechaModificacion";
		public const string IdEstado_EntityColumn = "IdEstado";

        #endregion

        
        #region << Atributtes >>

		private int _id;
		private int _idEmpresa;
		private EmpresaEntity _IdEmpresaAsEmpresa;
		private string _ruc;
		private RucEntity _RucAsRuc;
		private string _mes;
		private string _fecha;
		private decimal _presupuesto;
		private string _ipIngreso;
		private string _usuarioIngreso;
		private DateTime _fechaIngreso;
		private string _ipModificacion;
		private string _usuarioModificacion;
		private DateTime? _fechaModificacion;
		private short _idEstado;

        #endregion

        #region << Properties >>

		/// <summary> 
		/// Get or sets a obligatory value of Id. 
		/// </summary>
		public virtual int Id
		{
			get
			{
				return _id;
			}
			set
			{
				if (_id != value && CurrentState != EntityStatesEnum.New && CurrentState != EntityStatesEnum.Deleted)
				{
					CurrentState = EntityStatesEnum.Updated;
				}
				_id = value;
			}
		}

		/// <summary> 
		/// Get or sets a obligatory value of IdEmpresa. 
		/// </summary>
		public virtual int IdEmpresa
		{
			get
			{
				return _idEmpresa;
			}
			set
			{
				if (_idEmpresa != value && CurrentState != EntityStatesEnum.New && CurrentState != EntityStatesEnum.Deleted)
				{
					CurrentState = EntityStatesEnum.Updated;
				}
				_idEmpresa = value;
			}
		}

		public virtual EmpresaEntity IdEmpresaAsEmpresa
		{
			get
			{
				return _IdEmpresaAsEmpresa;
			}
			set
			{
				_IdEmpresaAsEmpresa = value;
			}
		}

		public virtual string IdEmpresa_DisplayMember
		{
			get
			{
				if(IdEmpresaAsEmpresa!= null ) 
				{
					return IdEmpresaAsEmpresa.ToString();
				}
				return "";
			}
		}

		/// <summary> 
		/// Get or sets a obligatory value of Ruc. 
		/// </summary>
		public virtual string Ruc
		{
			get
			{
				return _ruc;
			}
			set
			{
				if (_ruc != value && CurrentState != EntityStatesEnum.New && CurrentState != EntityStatesEnum.Deleted)
				{
					CurrentState = EntityStatesEnum.Updated;
				}
				_ruc = value;
			}
		}

		public virtual RucEntity RucAsRuc
		{
			get
			{
				return _RucAsRuc;
			}
			set
			{
				_RucAsRuc = value;
			}
		}

		public virtual string Ruc_DisplayMember
		{
			get
			{
				if(RucAsRuc!= null ) 
				{
					return RucAsRuc.ToString();
				}
				return "";
			}
		}

		/// <summary> 
		/// Get or sets a obligatory value of Mes. 
		/// </summary>
		public virtual string Mes
		{
			get
			{
				return _mes;
			}
			set
			{
				if (_mes != value && CurrentState != EntityStatesEnum.New && CurrentState != EntityStatesEnum.Deleted)
				{
					CurrentState = EntityStatesEnum.Updated;
				}
				_mes = value;
			}
		}

		/// <summary> 
		/// Get or sets a obligatory value of Fecha. 
		/// </summary>
		public virtual string Fecha
		{
			get
			{
				return _fecha;
			}
			set
			{
				if (_fecha != value && CurrentState != EntityStatesEnum.New && CurrentState != EntityStatesEnum.Deleted)
				{
					CurrentState = EntityStatesEnum.Updated;
				}
				_fecha = value;
			}
		}

		/// <summary> 
		/// Get or sets a obligatory value of Presupuesto. 
		/// </summary>
		public virtual decimal Presupuesto
		{
			get
			{
				return _presupuesto;
			}
			set
			{
				if (_presupuesto != value && CurrentState != EntityStatesEnum.New && CurrentState != EntityStatesEnum.Deleted)
				{
					CurrentState = EntityStatesEnum.Updated;
				}
				_presupuesto = value;
			}
		}

		/// <summary> 
		/// Get or sets a obligatory value of IpIngreso. 
		/// </summary>
		public virtual string IpIngreso
		{
			get
			{
				return _ipIngreso;
			}
			set
			{
				if (_ipIngreso != value && CurrentState != EntityStatesEnum.New && CurrentState != EntityStatesEnum.Deleted)
				{
					CurrentState = EntityStatesEnum.Updated;
				}
				_ipIngreso = value;
			}
		}

		/// <summary> 
		/// Get or sets a obligatory value of UsuarioIngreso. 
		/// </summary>
		public virtual string UsuarioIngreso
		{
			get
			{
				return _usuarioIngreso;
			}
			set
			{
				if (_usuarioIngreso != value && CurrentState != EntityStatesEnum.New && CurrentState != EntityStatesEnum.Deleted)
				{
					CurrentState = EntityStatesEnum.Updated;
				}
				_usuarioIngreso = value;
			}
		}

		/// <summary> 
		/// Get or sets a obligatory value of FechaIngreso. 
		/// </summary>
		public virtual DateTime FechaIngreso
		{
			get
			{
				return _fechaIngreso;
			}
			set
			{
				if (_fechaIngreso != value && CurrentState != EntityStatesEnum.New && CurrentState != EntityStatesEnum.Deleted)
				{
					CurrentState = EntityStatesEnum.Updated;
				}
				_fechaIngreso = value;
			}
		}

		/// <summary> 
		/// Get or sets a optional value of IpModificacion. 
		/// </summary>
		public virtual string IpModificacion
		{
			get
			{
				return _ipModificacion;
			}
			set
			{
				if (_ipModificacion != value && CurrentState != EntityStatesEnum.New && CurrentState != EntityStatesEnum.Deleted)
				{
					CurrentState = EntityStatesEnum.Updated;
				}
				_ipModificacion = value;
			}
		}

		/// <summary> 
		/// Get or sets a optional value of UsuarioModificacion. 
		/// </summary>
		public virtual string UsuarioModificacion
		{
			get
			{
				return _usuarioModificacion;
			}
			set
			{
				if (_usuarioModificacion != value && CurrentState != EntityStatesEnum.New && CurrentState != EntityStatesEnum.Deleted)
				{
					CurrentState = EntityStatesEnum.Updated;
				}
				_usuarioModificacion = value;
			}
		}

		/// <summary> 
		/// Get or sets a optional value of FechaModificacion. 
		/// </summary>
		public virtual DateTime? FechaModificacion
		{
			get
			{
				return _fechaModificacion;
			}
			set
			{
				if (_fechaModificacion != value && CurrentState != EntityStatesEnum.New && CurrentState != EntityStatesEnum.Deleted)
				{
					CurrentState = EntityStatesEnum.Updated;
				}
				_fechaModificacion = value;
			}
		}

		/// <summary> 
		/// Get or sets a obligatory value of IdEstado. 
		/// </summary>
		public virtual short IdEstado
		{
			get
			{
				return _idEstado;
			}
			set
			{
				if (_idEstado != value && CurrentState != EntityStatesEnum.New && CurrentState != EntityStatesEnum.Deleted)
				{
					CurrentState = EntityStatesEnum.Updated;
				}
				_idEstado = value;
			}
		}

 
        #endregion
        
        
        public PresupuestoFacturacionEntityBase ()
        {
            SetNewState();
        }
        
        
        internal PresupuestoFacturacionEntity CopyBase()
        {
          PresupuestoFacturacionEntity copy = new PresupuestoFacturacionEntity();
          copy.Id = this.Id;
          copy.IdEmpresa = this.IdEmpresa;
          copy.Ruc = this.Ruc;
          copy.Mes = this.Mes;
          copy.Fecha = this.Fecha;
          copy.Presupuesto = this.Presupuesto;
          copy.IpIngreso = this.IpIngreso;
          copy.UsuarioIngreso = this.UsuarioIngreso;
          copy.FechaIngreso = this.FechaIngreso;
          copy.IpModificacion = this.IpModificacion;
          copy.UsuarioModificacion = this.UsuarioModificacion;
          copy.FechaModificacion = this.FechaModificacion;
          copy.IdEstado = this.IdEstado;
			if( this.IdEmpresaAsEmpresa!=null)
			{
				copy.IdEmpresaAsEmpresa = this.IdEmpresaAsEmpresa.Copy(); 
			}
			if( this.RucAsRuc!=null)
			{
				copy.RucAsRuc = this.RucAsRuc.Copy(); 
			}

          return copy;
          
        }
        
        #region << Entity State Methods >>
        public void RollBackChildrensState()
        {
			if( _IdEmpresaAsEmpresa != null )
			{
				if (_IdEmpresaAsEmpresa.PreviousState != EntityStatesEnum.None)_IdEmpresaAsEmpresa.RollBackState();
			}
			if( _RucAsRuc != null )
			{
				if (_RucAsRuc.PreviousState != EntityStatesEnum.None)_RucAsRuc.RollBackState();
			}
             
        }
        
        internal void SetStateBase(EntityStatesEnum state)
        {
			this.CurrentState=state;
			if( _IdEmpresaAsEmpresa != null )
			{
				if (_IdEmpresaAsEmpresa.CurrentState != state)_IdEmpresaAsEmpresa.SetState(state);
			}
			if( _RucAsRuc != null )
			{
				if (_RucAsRuc.CurrentState != state)_RucAsRuc.SetState(state);
			}
             
        }
        #endregion
        
        private bool __selected;

        public bool __Selected
        {
            get { return __selected; }
            set { __selected = value; }
        }
        
        
#region << Children >>

        
#endregion
        
        
        
    }
}

