    
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Amonsys Software Factory.
//     Template: Speed Developer FrameWork Version 1.0 (For Windows Applications)
//     Web Site: http://www.amonsys.com/SDF
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



using System;
using System.Collections.Generic;
using System.Text;

namespace ER.BE
{
   
     [System.Serializable]         
     public partial class ProvinciaEntityCollection : List<ProvinciaEntity>
    {
    
	
		#region << Get Parents Methods >>
		
		public PaisEntityCollection GetPaisFromIdPais()
		{
			PaisEntityCollection parentCollection = new PaisEntityCollection();

			foreach(ProvinciaEntity entity in this)
			{
				if(entity.IdPaisAsPais != null)
				{
					if(parentCollection.GetByPK(entity.IdPaisAsPais.Id) == null)
					{
						parentCollection.Add(entity.IdPaisAsPais);
					}
				}
			}

			return parentCollection;
		}

		
		#endregion

		#region << Entity State Methods >>

        public void SetState(EntityStatesEnum state)
        {
			foreach (ProvinciaEntity entity in this)
            {
                entity.SetState(state);
            }          
        }
        
        public void RollBackState()
        {
            foreach (ProvinciaEntity entity in this)
            {
                entity.RollBackState();
            }
        }
        
        #endregion
        
        public ProvinciaEntity GetByPK(int Id)
        {
            foreach (ProvinciaEntity entity in this)
            {
                if(entity.Id == Id)
                {
                	return entity;
                }
            }
            
            return null;
        }
        
        
        public ProvinciaEntityCollection CreateCollection()
        {
        	return new ProvinciaEntityCollection();
        }
        
          
    }
}
