    
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Amonsys Software Factory.
//     Template: Speed Developer FrameWork Version 1.0 (For Windows Applications)
//     Web Site: http://www.amonsys.com/SDF
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



using System;
using System.Collections.Generic;
using System.Text;

namespace ER.BE
{
    [System.Serializable] 
    public partial class StockFindParameterEntity
    {
     
        #region << Atributtes >>

		private string _id;
		private int _idEmpresa = int.MinValue;
		private string _tipo;
		private string _idSalidaEntrada;
		private string _idDetalle;
		private int _idProducto = int.MinValue;
		private int _idLocal = int.MinValue;
		private DateTime _fecha;
		private decimal _cantidad = decimal.MinValue;
		private decimal _valorUnitario = decimal.MinValue;
		private decimal _valorTotal = decimal.MinValue;
		private int _idTipoUnidad = int.MinValue;
		private decimal _cantidadTipoUnidad = decimal.MinValue;
		private decimal _stockInventario = decimal.MinValue;
		private decimal _costoPromedioPonderado = decimal.MinValue;
		private decimal _saldoInventario = decimal.MinValue;
		private short _idEstado = short.MinValue;

        #endregion

        #region << Properties >>

		public string Id
		{
			get
			{
				return _id;
			}
			set
			{
				_id = value;
			}
		}

		public int IdEmpresa
		{
			get
			{
				return _idEmpresa;
			}
			set
			{
				_idEmpresa = value;
			}
		}

		public string Tipo
		{
			get
			{
				return _tipo;
			}
			set
			{
				_tipo = value;
			}
		}

		public string IdSalidaEntrada
		{
			get
			{
				return _idSalidaEntrada;
			}
			set
			{
				_idSalidaEntrada = value;
			}
		}

		public string IdDetalle
		{
			get
			{
				return _idDetalle;
			}
			set
			{
				_idDetalle = value;
			}
		}

		public int IdProducto
		{
			get
			{
				return _idProducto;
			}
			set
			{
				_idProducto = value;
			}
		}

		public int IdLocal
		{
			get
			{
				return _idLocal;
			}
			set
			{
				_idLocal = value;
			}
		}

		public DateTime Fecha
		{
			get
			{
				return _fecha;
			}
			set
			{
				_fecha = value;
			}
		}

		public decimal Cantidad
		{
			get
			{
				return _cantidad;
			}
			set
			{
				_cantidad = value;
			}
		}

		public decimal ValorUnitario
		{
			get
			{
				return _valorUnitario;
			}
			set
			{
				_valorUnitario = value;
			}
		}

		public decimal ValorTotal
		{
			get
			{
				return _valorTotal;
			}
			set
			{
				_valorTotal = value;
			}
		}

		public int IdTipoUnidad
		{
			get
			{
				return _idTipoUnidad;
			}
			set
			{
				_idTipoUnidad = value;
			}
		}

		public decimal CantidadTipoUnidad
		{
			get
			{
				return _cantidadTipoUnidad;
			}
			set
			{
				_cantidadTipoUnidad = value;
			}
		}

		public decimal StockInventario
		{
			get
			{
				return _stockInventario;
			}
			set
			{
				_stockInventario = value;
			}
		}

		public decimal CostoPromedioPonderado
		{
			get
			{
				return _costoPromedioPonderado;
			}
			set
			{
				_costoPromedioPonderado = value;
			}
		}

		public decimal SaldoInventario
		{
			get
			{
				return _saldoInventario;
			}
			set
			{
				_saldoInventario = value;
			}
		}

		public short IdEstado
		{
			get
			{
				return _idEstado;
			}
			set
			{
				_idEstado = value;
			}
		}

 
        #endregion

        public bool IsValid(StockEntity _entity)
        { 
			if(this.IdEmpresa != int.MinValue)
			{
				if(this.IdEmpresa!=_entity.IdEmpresa)
				{
					return false;
				}
			}

			if(!String.IsNullOrEmpty(this.Tipo))
			{
				if(this.Tipo!=_entity.Tipo)
				{
					return false;
				}
			}

			if(!String.IsNullOrEmpty(this.IdSalidaEntrada))
			{
				if(this.IdSalidaEntrada!=_entity.IdSalidaEntrada)
				{
					return false;
				}
			}

			if(!String.IsNullOrEmpty(this.IdDetalle))
			{
				if(this.IdDetalle!=_entity.IdDetalle)
				{
					return false;
				}
			}

			if(this.IdProducto != int.MinValue)
			{
				if(this.IdProducto!=_entity.IdProducto)
				{
					return false;
				}
			}

			if(this.IdLocal != int.MinValue)
			{
				if(this.IdLocal!=_entity.IdLocal)
				{
					return false;
				}
			}

			if(this.Fecha != DateTime.MinValue)
			{
				if(this.Fecha!=_entity.Fecha)
				{
					return false;
				}
			}

			if(this.Cantidad != decimal.MinValue)
			{
				if(this.Cantidad!=_entity.Cantidad)
				{
					return false;
				}
			}

			if(this.ValorUnitario != decimal.MinValue)
			{
				if(this.ValorUnitario!=_entity.ValorUnitario)
				{
					return false;
				}
			}

			if(this.ValorTotal != decimal.MinValue)
			{
				if(this.ValorTotal!=_entity.ValorTotal)
				{
					return false;
				}
			}

			if(this.IdTipoUnidad != int.MinValue)
			{
				if(this.IdTipoUnidad!=_entity.IdTipoUnidad)
				{
					return false;
				}
			}

			if(this.CantidadTipoUnidad != decimal.MinValue)
			{
				if(this.CantidadTipoUnidad!=_entity.CantidadTipoUnidad)
				{
					return false;
				}
			}

			if(this.StockInventario != decimal.MinValue)
			{
				if(this.StockInventario!=_entity.StockInventario)
				{
					return false;
				}
			}

			if(this.CostoPromedioPonderado != decimal.MinValue)
			{
				if(this.CostoPromedioPonderado!=_entity.CostoPromedioPonderado)
				{
					return false;
				}
			}

			if(this.SaldoInventario != decimal.MinValue)
			{
				if(this.SaldoInventario!=_entity.SaldoInventario)
				{
					return false;
				}
			}

			if(this.IdEstado != short.MinValue)
			{
				if(this.IdEstado!=_entity.IdEstado)
				{
					return false;
				}
			}

     

			return true;       
        }

     

    }
}

