    
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Amonsys Software Factory.
//     Template: Speed Developer FrameWork Version 1.0 (For Windows Applications)
//     Web Site: http://www.amonsys.com/SDF
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



using System;
using System.Collections.Generic;
using System.Text;

namespace ER.BE
{
   
     [System.Serializable]         
     public partial class UsuarioLocalBodegaEntityCollection : List<UsuarioLocalBodegaEntity>
    {
    
	
		#region << Get Parents Methods >>
		
		public LocalBodegaEntityCollection GetLocalBodegaFromIdLocalBodega()
		{
			LocalBodegaEntityCollection parentCollection = new LocalBodegaEntityCollection();

			foreach(UsuarioLocalBodegaEntity entity in this)
			{
				if(entity.IdLocalBodegaAsLocalBodega != null)
				{
					if(parentCollection.GetByPK(entity.IdLocalBodegaAsLocalBodega.Id) == null)
					{
						parentCollection.Add(entity.IdLocalBodegaAsLocalBodega);
					}
				}
			}

			return parentCollection;
		}

		public UsuarioEntityCollection GetUsuarioFromInicioSesion()
		{
			UsuarioEntityCollection parentCollection = new UsuarioEntityCollection();

			foreach(UsuarioLocalBodegaEntity entity in this)
			{
				if(entity.InicioSesionAsUsuario != null)
				{
					if(parentCollection.GetByPK(entity.InicioSesionAsUsuario.InicioSesion) == null)
					{
						parentCollection.Add(entity.InicioSesionAsUsuario);
					}
				}
			}

			return parentCollection;
		}

		
		#endregion

		#region << Entity State Methods >>

        public void SetState(EntityStatesEnum state)
        {
			foreach (UsuarioLocalBodegaEntity entity in this)
            {
                entity.SetState(state);
            }          
        }
        
        public void RollBackState()
        {
            foreach (UsuarioLocalBodegaEntity entity in this)
            {
                entity.RollBackState();
            }
        }
        
        #endregion
        
        public UsuarioLocalBodegaEntity GetByPK(int Id)
        {
            foreach (UsuarioLocalBodegaEntity entity in this)
            {
                if(entity.Id == Id)
                {
                	return entity;
                }
            }
            
            return null;
        }
        
        
        public UsuarioLocalBodegaEntityCollection CreateCollection()
        {
        	return new UsuarioLocalBodegaEntityCollection();
        }
        
          
    }
}
