// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ER.DA.Models;
using ER.DA.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ER.DA.Repositories.Configurations
{
    public partial class DetalleMedioCobroConfiguration : IEntityTypeConfiguration<DetalleMedioCobro>
    {
        public void Configure(EntityTypeBuilder<DetalleMedioCobro> entity)
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Descripcion)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.FechaIngreso).HasColumnType("datetime");
            entity.Property(e => e.FechaModificacion).HasColumnType("datetime");
            entity.Property(e => e.IdCobroDebito)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.IpIngreso)
                .IsRequired()
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.IpModificacion)
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.UsuarioIngreso)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UsuarioModificacion)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Valor).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.IdCobroDebitoNavigation).WithMany(p => p.DetalleMedioCobro)
                .HasForeignKey(d => d.IdCobroDebito)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DetalleMedioCobro_CobroDebito");

            entity.HasOne(d => d.IdDetalleCobroNavigation).WithMany(p => p.DetalleMedioCobro)
                .HasForeignKey(d => d.IdDetalleCobro)
                .HasConstraintName("FK_DetalleMedioCobro_DetalleCobro");

            entity.HasOne(d => d.IdMedioPagoNavigation).WithMany(p => p.DetalleMedioCobro)
                .HasForeignKey(d => d.IdMedioPago)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DetalleMedioCobro_MedioPago");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DetalleMedioCobro> entity);
    }
}
